=== ROHIT-KUMAR-CGC16133/ILOSAPIAutomation/src/test/resources/schemas/legal_property_list_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "application_id": { "type": "string" },
          "loan_amount": { "type": "string" },
          "portfolio_type": { "type": "string" },
          "legal_stage": { "type": "string" },
          "home_branch_code": { "type": ["string", "null"] },
          "loan_branch": { "type": ["string", "null"] },
          "property_ids": { "type": ["string", "null"] },
          "queries": { "type": ["string", "null"] },
          "query_raised_on": { "type": "integer" },
          "applicant_name": { "type": "string" },
          "transaction_type": { "type": ["string", "null"] },
          "vendors": { "type": ["string", "null"] },
          "updated_at": { "type": ["string", "null"] },
          "homeAccess": { "type": "integer" },
          "filter": { "type": ["string", "null"] },
          "bt_application_id": { "type": ["string", "null"] },
          "case_bt": { "type": ["string", "null"] },
          "case_topup": { "type": ["string", "null"] },
          "case_bt_topup": { "type": ["string", "null"] },
          "property_id": { "type": "integer" },
          "property_type": { "type": "string" },
          "vendor_email": { "type": ["string", "null"] },
          "property_address": {
            "type": "object",
            "properties": {
              "area": { "type": "string" },
              "city": { "type": "string" },
              "state": { "type": "string" },
              "taluka": { "type": "string" },
              "pincode": { "type": "integer" },
              "district": { "type": "string" },
              "landmark": { "type": "string" },
              "address_line_1": { "type": "string" },
              "address_line_2": { "type": "string" },
              "same_as_current_address": { "type": "boolean" },
              "same_as_permanent_address": { "type": "boolean" }
            },
            "required": [
              "area",
              "city",
              "state",
              "taluka",
              "pincode",
              "district",
              "address_line_1",
              "address_line_2",
              "same_as_current_address",
              "same_as_permanent_address"
            ]
          },
          "property_ownership": {
            "type": "object",
            "properties": {
              "type": { "type": "string" },
              "property_owners": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "owner_id": { "type": "integer" },
                    "owner_name": { "type": "string" },
                    "owner_type": { "type": "string" }
                  },
                  "required": ["owner_id", "owner_name", "owner_type"]
                }
              }
            },
            "required": ["type", "property_owners"]
          },
          "vendor_remarks": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "remark_id": { "type": "integer" },
                "send_back_prop_id": { "type": "integer" },
                "re_trigger_prop_id": { "type": "integer" },
                "text": { "type": "string" },
                "section": { "type": "string" },
                "sub_section": { "type": "string" },
                "role": { "type": "string" },
                "created_by": {
                  "type": "object",
                  "properties": {
                    "name": { "type": ["string", "null"] },
                    "email": { "type": "string" },
                    "emp_code": { "type": "string" },
                    "emp_name": { "type": "string" },
                    "designation": { "type": "string" },
                    "branch_code": { "type": ["string", "null"] },
                    "allowed_branches": {
                      "type": "array",
                      "items": { "type": "string" }
                    }
                  },
                  "required": ["email", "emp_code", "emp_name", "designation", "allowed_branches"]
                },
                "created_at": { "type": "integer" },
                "property_ids": {
                  "type": "array",
                  "items": { "type": "integer" }
                }
              },
              "required": ["remark_id", "text", "section", "sub_section", "role", "created_by", "created_at"]
            }
          },
          "sendback_remarks": { "type": "array" },
          "legal_reference": {
            "type": "object",
            "properties": {
              "legal_branch_code": { "type": "string" },
              "legal_coordinator": { "type": "string" },
              "assigned_on": { "type": ["string", "null"] },
              "legal_manager": { "type": "string" },
              "legal_approver_designation": { "type": ["string", "null"] },
              "legal_branch_name": { "type": ["string", "null"] },
              "legal_coordinator_emp_code": { "type": ["string", "null"] },
              "legal_coordinator_name": { "type": ["string", "null"] },
              "la_status": { "type": "string" },
              "legal_approver_submitted_on": { "type": "integer" },
              "legal_approver_assigned_on": { "type": ["string", "null"] },
              "legal_manager_assigned_on": { "type": "integer" }
            },
            "required": ["legal_branch_code", "legal_coordinator", "legal_manager", "la_status", "legal_approver_submitted_on", "legal_manager_assigned_on"]
          },
          "vendor_reference": {
            "type": "object",
            "properties": {
              "re_trigger_prop_id": { "type": "integer" },
              "vendor_email": { "type": "string" },
              "vendor_id": { "type": "string" },
              "vendor_name": { "type": "string" },
              "assigned_on": { "type": "integer" },
              "created_at": { "type": "integer" },
              "created_by": { "type": "string" },
              "v_type": { "type": "string" }
            },
            "required": ["vendor_email", "vendor_id", "vendor_name", "assigned_on", "created_at", "created_by", "v_type"]
          },
          "is_referred": { "type": ["boolean", "null"] },
          "is_reassign": { "type": ["boolean", "null"] },
          "is_retrigger": { "type": "boolean" },
          "is_disabled": { "type": ["boolean", "null"] },
          "legal_opinion_report": { "type": "string" },
          "search_report": { "type": "string" },
          "is_send_back": { "type": "boolean" },
          "decision": { "type": "string" },
          "query_resolved_on": { "type": ["string", "null"] }
        },
        "required": ["id", "application_id", "loan_amount", "portfolio_type", "legal_stage", "query_raised_on", "applicant_name", "homeAccess", "property_id", "property_type", "property_address", "property_ownership", "vendor_remarks", "legal_reference", "vendor_reference", "is_retrigger", "legal_opinion_report", "search_report", "is_send_back", "decision"]
      }
    },
    "msg": { "type": "string" },
    "count": { "type": "integer" },
    "is_submitted": { "type": "boolean" },
    "refer_user": { "type": "boolean" },
    "is_single_prop": { "type": "boolean" }
  },
  "required": ["data", "msg", "count", "is_submitted", "refer_user", "is_single_prop"]
}

=== ROHIT-KUMAR-CGC16133/ILOSAPIAutomation/src/test/resources/response_validation/legal_property_list_res.json
{
  "data": [
    {
      "id": "682ec1a476e73a98539fb20e",
      "application_id": "146387",
      "loan_amount": "1400000",
      "portfolio_type": "msme tl",
      "legal_stage": "ASSIGNED_TO_CREDIT",
      "home_branch_code": null,
      "loan_branch": null,
      "property_ids": null,
      "queries": null,
      "query_raised_on": 1748017987853,
      "applicant_name": "VIKAS",
      "transaction_type": null,
      "vendors": null,
      "updated_at": null,
      "homeAccess": 1,
      "filter": null,
      "bt_application_id": null,
      "case_bt": null,
      "case_topup": null,
      "case_bt_topup": null,
      "property_id": 1,
      "property_type": "residential",
      "vendor_email": null,
      "property_address": {
        "area": "MANDSAUR",
        "city": "MANDSAUR",
        "state": "MADHYA PRADESH",
        "taluka": "MANDSAUR",
        "pincode": 458883,
        "district": "MANDSAUR",
        "landmark": "",
        "address_line_1": "KHASRA NO 297 PH NO 09 GRAM CHANDWASA ",
        "address_line_2": "TEHSIL SHAMGARH JILA MANDSAUR",
        "same_as_current_address": true,
        "same_as_permanent_address": false
      },
      "property_ownership": {
        "type": "joint",
        "property_owners": [
          {
            "owner_id": 313081,
            "owner_name": "DAYARAM PRAJAPATI",
            "owner_type": "Non-Financial Co-Applicant"
          },
          {
            "owner_id": 313086,
            "owner_name": "BHAGVANTI BAI",
            "owner_type": "Non-Financial Co-Applicant"
          }
        ]
      },
      "vendor_remarks": [
        {
          "remark_id": 1,
          "send_back_prop_id": -1,
          "re_trigger_prop_id": -1,
          "text": "Legal Report is okay",
          "section": "legal",
          "sub_section": "vendor",
          "role": "LV",
          "created_by": {
            "name": null,
            "email": "RajeshKumarRathore@capriapps.in",
            "emp_code": "",
            "emp_name": "",
            "designation": "",
            "branch_code": null,
            "allowed_branches": [

            ]
          },
          "created_at": 1748082363335,
          "property_ids": [
            1
          ]
        }
      ],
      "sendback_remarks": [

      ],
      "legal_reference": {
        "legal_branch_code": "surshg01",
        "legal_coordinator": "Ankush.Sharma2@caprihomeloans.com",
        "assigned_on": null,
        "legal_manager": "Virendra.Chouhan@caprihomeloans.com",
        "legal_approver_designation": null,
        "legal_branch_name": null,
        "legal_coordinator_emp_code": null,
        "legal_coordinator_name": null,
        "la_status": "APPROVE",
        "legal_approver_submitted_on": 1748095330805,
        "legal_approver_assigned_on": null,
        "legal_manager_assigned_on": 1748083930650
      },
      "vendor_reference": {
        "re_trigger_prop_id": -1,
        "vendor_email": "RajeshKumarRathore@capriapps.in",
        "vendor_id": "661162c4d8b2bbfd3e93c2ee",
        "vendor_name": "RAJESH KUMAR RATHORE",
        "assigned_on": 1748072699789,
        "created_at": 1748072699789,
        "created_by": "Ankush.Sharma2@caprihomeloans.com",
        "v_type": "external"
      },
      "is_referred": null,
      "is_reassign": null,
      "is_retrigger": false,
      "is_disabled": null,
      "legal_opinion_report": "loanxpress-cgcl-prod-backend/upload_docs/application_form/LORreport_146387_1_1748081390542.pdf",
      "search_report": "loanxpress-cgcl-prod-backend/upload_docs/user/146387_Tsr_Shamgarh_2.pdf_1748082325363.pdf",
      "is_send_back": false,
      "decision": "positive",
      "query_resolved_on": null
    }
  ],
  "msg": "Success",
  "count": 1,
  "is_submitted": true,
  "refer_user": true,
  "is_single_prop": true
}
